export const routersPaths = {
  common: '/',
  users: '/users',
  blogs: '/blogs',
  posts: '/posts',
  comments: '/comments',
  testing: '/testing',
  inTesting: '/all-data',
  security: '/security',
  inSecurity: '/devices',
  auth: '/auth',
  login: '/login',
  me: '/me',
  registration: '/registration',
  registrationConfirmation: '/registration-confirmation',
  registrationEmailResending: '/registration-email-resending',
  passwordRecovery: '/password-recovery',
  newPassword: '/new-password',
  refreshToken: '/refresh-token',
  logout: '/logout',
};
